### ISSUE TITLE
LCD2004 Pin Out

### ISSUE THREAD

**Issue by ghost** [melvinchng/AnetA8_MKSBase1.5#1]
I know you had mentioned a different lcd on here but is there anyway to get the pin out right for the stock LCD2004. It seems to be already in the mainline marlin but i cant figure out what pin out to change. thanks

**Comment by melvinchng** [comment]
Yes, it is possible. You need to obtain the firmware for 2004, compared it with TFT edition (from this repository). I believed the code that defines the LCDs is in `configuration.h`.

**Comment by melvinchng** [comment]
Close as no follow-up feedback from original issue creator.
