### ISSUE TITLE
Pin Numbers

### ISSUE THREAD

**Issue by jorgan202** [melvinchng/AnetA8_MKSBase1.5#2]
Please can someone tell me where #define PS_ON_PIN           **9**, ie, pin 9 is in the MKS Base board 1.5 is, so that i can use a relay to switch the printer off whens its done

Please please

**Comment by melvinchng** [comment]
You do not necessarily need PIN 9, you can use any available ports that are on the board for PIN 9. The best is to contact the manufacturer to see which pins are available. By looking at the data sheet, there are a few available pins on the board, but you need to figure out how to use them.

**Comment by jorgan202** [comment]
Unfortunately the manufacture is not interested.  When you say there are some available, how do I identify them in terms of numbering, so when you see D50 or A11, A12 what does that actually mean and how do they tie back to the number used in the pins.h file?  Sorry if this sounds dumb but I cant seem to reconcile whats on the board and how pins.h addresses those pins?  Thanks

**Comment by melvinchng** [comment]
I no longer own the printer as I sold it away to my friend. If you take a look at the board, you might discover some Axx or Dxx (where xx is the pin number, A = Analog, D = Digital) exposed pins on the board. You should be able to use any of the Digital pins. 

One dumb question, do you have your printer controller running from a separate power source? It does not make sense to me if you have a printer, but running on the same power source.

**Comment by jorgan202** [comment]
Thanks, no such thing as a dumb question. Its a separate supply, By using a relay with an over ride switch on the 220V supply, you can switch the power off to the printer when its done using the M80 and M81 function

**Comment by melvinchng** [comment]
Have you heard of OctoPi? The easier and recommended way is to use an OctoPi, which runs on Raspberry Pi. That's the usual way of what people do. It might cost more but probably works better for your case since you can easily add a camera, lights, and other feature to your printer.
