### ISSUE TITLE
How to Enable 12/24V Pin on Marlin

### ISSUE THREAD

**Issue by Vitoin** [melvinchng/AnetA8_MKSBase1.5#3]
Hi

I am trying to turn on this pin for extruder fan, but not sure which pin to use. Just wondering if anyone knows how to enable this Pin. #define E0_AUTO_FAN_PIN -1

* Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
**#define E0_AUTO_FAN_PIN -1**
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed

Thanks for help

**Comment by melvinchng** [comment]
Does the firmware in my repository support this feature?

**Comment by melvinchng** [comment]
Follow up message is not received. Issue closed.
